### ISSUE TITLE
Cannot install PyQt6

### ISSUE THREAD

**Issue by callegar** [pyston/pyston_v2#290]
Trying to install `retext` with pyston fails, while it goes fine with regular cpython.

Issue appears to be with PyQt6

Getting:

```
  Using cached PyQt6-6.4.0.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/home/callegar/PythonEnvs/Pyston2.3.5-utils/lib/python3.8-pyston2.3/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/callegar/PythonEnvs/Pyston2.3.5-utils/lib/python3.8-pyston2.3/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/callegar/PythonEnvs/Pyston2.3.5-utils/lib/python3.8-pyston2.3/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/callegar/PythonEnvs/Pyston2.3.5-utils/lib/python3.8-pyston2.3/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-5522mhh7/overlay/lib/python3.8-pyston2.3/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-5522mhh7/overlay/lib/python3.8-pyston2.3/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-5522mhh7/overlay/lib/python3.8-pyston2.3/site-packages/sipbuild/project.py", line 601, in setup
          self.update(tool)
        File "project.py", line 162, in update
      sipbuild.exceptions.UserException
      [end of output]
```

**Comment by kmod** [comment]
Looking into this a bit, it looks like this is a pyqt issue, not a pyston issue: when I build pyqt6 from source on CPython, it fails with the same error message.

By searching for the error message I've found some other people running into this problem, and the only solution offered was to upgrade pip which did not work for me (on pyston or cpython). Sorry I can't be of more help :/

**Comment by callegar** [comment]
That looks weird. I have both cpython and pyston virtual envs and the only major difference is that cpython is 3.10 while pyston is 3.8. I can install retext in the cpython virtual env with `pip install`, but it fails as shown above with the pyston virtual env. Same commands. The only think I can think of is that something has a pre-made wheel for cpython 3.10 and not for python 3.8 or pyston. May that be the case?

**Comment by kmod** [comment]
Yes, that is it exactly. You have to tell pip to install from source, otherwise it probably gets a prebuilt wheel from pypi. You should be able to see this from the pip logs that pyston tries to compile it but cpython does not.

I only tested with cpython 3.8 (not 3.10) so there's a small chance that that's the issue, but I strongly suspect that their package has a build system that does not work by default. I did `pip install pyqt6 --no-binary pyqt6` and got the same error message for cpython 3.8

**Comment by kmod** [comment]
I'm going to close this but please feel free to reopen if there are further issues!
