### ISSUE TITLE
Gevent doesn't work.

### ISSUE THREAD

**Issue by clanet** [pyston/pyston_v2#43]
ubuntu 20.10  pyston 2.2

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import gevent.monkey
  File "/usr/lib/pyston3.8/site-packages/gevent/__init__.py", line 85, in <module>
    from gevent._config import config
  File "/usr/lib/pyston3.8/site-packages/gevent/_config.py", line 699, in <module>
    Loop().get()
  File "/usr/lib/pyston3.8/site-packages/gevent/_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "/usr/lib/pyston3.8/site-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/usr/lib/pyston3.8/site-packages/gevent/_config.py", line 219, in _import_one_of
    return self._import_one(item)
  File "/usr/lib/pyston3.8/site-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/usr/lib/pyston3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/libev/corecext.pyx", line 979, in init gevent.libev.corecext
SystemError: Bad call flags for CyFunction

**Comment by undingen** [comment]
Thanks for reporting the bug!
Seems to be the same issue as in https://github.com/pyston/pyston/issues/42
I'm currently investigating what caused it and how to fix it.

**Comment by undingen** [comment]
Cython 3.0.0a8 got released which contains the fix for pyston :fireworks: .
Installing gevent should now work again (tested with latest gevent 21.1.2 which previously failed).

Hope this resolves the issue for you.
