### ISSUE TITLE
Build failure on Fedora 34

### ISSUE THREAD

**Issue by kaber2** [pyston/pyston_v2#71]
Hello,

building the latest release on FC34 fails with:

```
mkdir -p pyston/build/aot
cd pyston/aot; LD_LIBRARY_PATH="`pwd`/../Release/nitrous/:`pwd`/../Release/pystol/" ../build/cpython_bc_install/usr/bin/python3 aot_gen.py --action=pretrace -o /home/user/src/test/pyston/pyston/build/aot/aot_pre_trace.c 
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "aot_gen.py", line 4, in <module>
    import ctypes
  File "/home/user/src/test/pyston/pyston/build/cpython_bc_install/usr/lib/python3.8-pyston2.3/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
make: *** [Makefile:285: pyston/build/aot/aot_pre_trace.c] Fehler 1
```

The _ctypes shared object is present in the cpython_bc_install direction in the following location:
```
./pyston/build/cpython_bc_install/usr/lib64/python3.8-pyston2.3/lib-dynload/_ctypes.pyston-23-x86_64-linux-gnu.so
```

But it seems there is something wrong with the search paths. Any ideas how to correct it? Thanks!

**Comment by undingen** [comment]
Sorry for the late repsonse, just came back from holiday.
We only tried building pyston on ubuntu for now :/. 
I suspect the issue is caused by us looking for `./pyston/build/cpython_bc_install/usr/lib/` instead of `./pyston/build/cpython_bc_install/usr/lib64/`.
If you are interested in adding fedora support I suggest creating a symlink for now and see if you run into more problems.
But I don't know if it will be easy to port or if there will be much more issues :/.

**Comment by mischievous** [comment]
This happened to me when I was building on AWS Linux (a weird version of redhat). 
1. pip3 install virualenv
2. Had to download and build gnu make (might be a AWS thing)
3. Had to download and build cmake (AWS?)
4. Had to download and build luajit (AWS?) 
5. sudo yum install libffi-devel.x86_64

Using the "make unopt -JX" was a non starter.  Had to just use "make -JX". 

I just did a make clean... not sure it actually did anthing... 

1. make -j2 # gcc: error: unrecognized command line option ‘-fcf-protection=none’; did you mean ‘-flto-partition=none’?
2. make unopt -j2 # gcc: error: unrecognized command line option ‘-fcf-protection=none’; did you mean ‘-flto-partition=none’?

**Comment by kmod** [comment]
Ah yes virtualenv is required for our build process; we have it as part of our Ubuntu instructions but if you knew how to translate that to Fedora we would greatly appreciate it.

Could you post what went wrong with `make unopt`? That should be a simpler target and more likely to work.

**Comment by mischievous** [comment]
I updated my previous comment.  I'm also starting to think that the first time I built it, it did not work but I was able to run pyston3 so I don't know what is going on. :(

What version of GCC you are building with?

**Comment by kmod** [comment]
`gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`, you?

**Comment by mischievous** [comment]
Grumble... gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-13).  I'm trying to update it to 10 which is the next version avaiable. 

More grumbling.  When installing gcc 10x it did not create the gcc links... Had to do that manually...

**Comment by mischievous** [comment]
Does this look correct?  Is there a test I can run?

Python 3.8.12 (heads/pyston_main:dc3de49cc6, Oct 14 2021, 10:59:39)
[Pyston 2.3.1, Clang 10.0.0 (https://github.com/llvm/llvm-project.git d32170dbd5b0d54436537b6b7] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by kmod** [comment]
Looks very promising! You should be able to do `pyston -m test` to run the CPython test suite

**Comment by mischievous** [comment]
== Tests result: FAILURE ==

390 tests OK.

1 test failed:
    test_subprocess

32 tests skipped:
    test_asdl_parser test_bz2 test_clinic test_curses test_dbm_gnu
    test_dbm_ndbm test_devpoll test_gdb test_idle test_kqueue
    test_lzma test_msilib test_ossaudiodev test_readline test_smtpnet
    test_socketserver test_sqlite test_startfile test_tcl test_timeout
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_urllib2net test_urllibnet test_winconsoleio test_winreg
    test_winsound test_xmlrpc_net test_zipfile64

**Comment by mischievous** [comment]
When building with "make -j2" getting a sqlite3 version too old error.  Looking into getting a newer sqlilte3.  This might also be a AWS Linux only issue and not a Fedora/Redhat issue.

**Comment by kmod** [comment]
I haven't seen the sqlite3 error, but I was seeing the test_subprocess issue and jpeg dependency issue on my branch, so we might have a problem on main, I'll check it out shortly.
