### ISSUE TITLE
Can Pyston run uvicorn server?

### ISSUE THREAD

**Issue by EmadMokhtar** [pyston/pyston_v2#76]
I'm building a Web API using FastAPI framework. It used `uvicorn` as a server to run the application. Can Pyston run uvicorn server? I'm not sure because I'm getting this error.

``` bash
uvicorn main:app --reload                                                                                        
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [31274] using watchgod
Traceback (most recent call last):
  File "/home/emadmokhtar/.pyenv/versions/fastapi-pyston/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/uvicorn/main.py", line 371, in main
    run(app, **kwargs)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/uvicorn/main.py", line 388, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/uvicorn/supervisors/basereload.py", line 43, in run
    self.startup()
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/envs/fastapi-pyston/lib/pyston3.8/site-packages/uvicorn/supervisors/basereload.py", line 64, in startup
    self.process.start()
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/popen_spawn_posix.py", line 39, in _launch
    from . import resource_tracker
  File "/home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/multiprocessing/resource_tracker.py", line 38, in <module>
    import _posixshmem
ImportError: /home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/lib-dynload/../../../lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
```

**Comment by EmadMokhtar** [comment]
It can run but without the `--reload` flag

``` bash
uvicorn main:app
INFO:     Started server process [31373]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by kmod** [comment]
It looks like this is via pyenv which uses our portable release, and it looks like sometimes our portable release is not fully portable and has issues like this. @undingen knows more but he's on vacation

In the mean time, you could try our .deb releases which are built for a specific distro and shouldn't have this sort of issue. This would also let you try our new 2.3 release which includes a number of compatibility improvements which could potentially help with a library like this.

**Comment by undingen** [comment]
Sorry for the delay, just came back from holiday.
I can confirm your issue and it's caused by mixing the distro shared libraries with the one included in the portable release used by pyenv. It seems like the portable release comes with a bunch of pitfalls and needs to overhaul. In the meantime either using the debian package or removing/renaming the included librt.so should fix the problem:
```bash
mv /home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/lib-dynload/../../../lib/librt.so.1 /home/emadmokhtar/.pyenv/versions/pyston-2.2/lib/pyston3.8/lib-dynload/../../../lib/librt.so.1_backup
```

**Comment by undingen** [comment]
I recreated the portable release with the #83 fix applied which fixes your problem - you can download it here:
https://github.com/pyston/pyston/releases/download/v2.3/pyston_2.3_portable-v3.tar.gz

**Comment by JohnMoutafis** [comment]
Ran on the same issue using pyston portable v.2.3.2 trying to start a FastAPI application via uvicorn:

`uvicorn apis.main:app --workers 4 --reload --debug`

**Comment by undingen** [comment]
What distro are you using? It seemed to work when I tried it out on ubuntu 20.04

**Comment by JohnMoutafis** [comment]
@undingen I am using Linux Mint 20.2

**Comment by undingen** [comment]
I seem not not be able to reproduce it using `linuxmintd/mint20.2-amd64` docker and the example from https://www.uvicorn.org/ using your command line args.
Could you please try reproduce/reduce it and and open a new bug.
Thanks
