### ISSUE TITLE
Segmentation fault while using python only code along the official binary without C extension

### ISSUE THREAD

**Issue by ytrezq** [pyston/pyston_v2#77]
Install [panoramix](https://github.com/palkeo/panoramix)

run `/usr/bin/panoramix "0xe0090Ec6895c087a393F0e45f1F85098A6c33bEf"`
The process crashes about 2 hours laters just before completion.

**Comment by kmod** [comment]
Sorry for the delay, we're on vacation and should check this out soon

**Comment by undingen** [comment]
Thanks for letting us know about this crash :).

I could reproduce the issue [1]. The cause is that decompiling `safeApprove` should raise a `RecursionError` but we removed the check in 2.3.
```
11:57:49 panoramix.decompiler Problem with safeApprove(address _param1, address _param2, uint256 _param3)
Traceback (most recent call last):
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/decompiler.py", line 177, in _decompile_with_loader
    trace = dec()
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/decompiler.py", line 169, in dec
    trace = make_whiles(trace)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/whiles.py", line 99, in make_whiles
    trace = simplify_trace(trace)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 176, in simplify_trace
    trace = cleanup_conds(trace)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  [Previous line repeated 3 more times]
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1216, in cleanup_conds
    if_false = cleanup_conds(if_false)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  [Previous line repeated 2 more times]
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1216, in cleanup_conds
    if_false = cleanup_conds(if_false)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  [Previous line repeated 2 more times]
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1216, in cleanup_conds
    if_false = cleanup_conds(if_false)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1215, in cleanup_conds
    if_true = cleanup_conds(if_true)
  [Previous line repeated 1 more time]
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1216, in cleanup_conds
    if_false = cleanup_conds(if_false)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/simplify.py", line 1219, in cleanup_conds
    ev = arithmetic.eval_bool(cond, symbolic=False)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/core/arithmetic.py", line 196, in eval_bool
    r = eval(exp)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/core/arithmetic.py", line 497, in eval
    return opcodes[exp[0]](*exp[1:])
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/core/arithmetic.py", line 463, in sge
    return sge(left, right) | eq(left, right)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/core/arithmetic.py", line 463, in sge
    return sge(left, right) | eq(left, right)
  File "/home/marius/dev/pyston_v2/pyston/build/unopt_env/lib/python3.8-pyston2.3/site-packages/panoramix/core/arithmetic.py", line 463, in sge
    return sge(left, right) | eq(left, right)
  [Previous line repeated 961 more times]
RecursionError: maximum recursion depth exceeded
11:57:49 panoramix.decompiler Parsing managers(address _param1)...
```
I confirmed that adding the check back fixes the problem.
BTW: seeing about 2x speed with pyston compared to cpython on this project on a different script

[1]: I copied out the raw bytes from here: https://oko.palkeo.com/0xe0090Ec6895c087a393F0e45f1F85098A6c33bEf/code/
instead of fetching it directly and passed it as argument to `panoramix`.

**Comment by undingen** [comment]
#85 fixed this issue
